[package]
name = "CLIManager"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clim"
path = "src/main.rs"

[dependencies]
clearscreen = "4.0.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
